[build]
builder = "dockerfiles"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "python web_interface/app_enhanced.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Variables d'environnement pour Railway
[env]
FLASK_ENV = "production"
PYTHONPATH = "/app/src:/app"
HOST = "0.0.0.0"
PORT = "$PORT"
LOG_LEVEL = "INFO"
ENVIRONMENT = "production"

# Configuration Railway spécifique
[settings]
generateDomain = true
