apiVersion: v1
kind: ServiceAccount
metadata:
  name: trading-bot-sa
  namespace: alphabeta808-trading

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trading-bot-role
  namespace: alphabeta808-trading
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trading-bot-rolebinding
  namespace: alphabeta808-trading
subjects:
- kind: ServiceAccount
  name: trading-bot-sa
  namespace: alphabeta808-trading
roleRef:
  kind: Role
  name: trading-bot-role
  apiGroup: rbac.authorization.k8s.io
