apiVersion: v1
kind: Secret
metadata:
  name: trading-secrets
  namespace: alphabeta808-trading
type: Opaque
data:
  # SECURITY WARNING: Replace these placeholder values with actual secrets
  # Generate base64 values using: echo -n "your_actual_secret" | base64
  # For production, use proper secret management tools like:
  # - Kubernetes External Secrets Operator
  # - HashiCorp Vault
  # - Azure Key Vault / AWS Secrets Manager / Google Secret Manager
  
  # Binance API credentials (REQUIRED - get from Binance account)
  binance-api-key: "REPLACE_WITH_BASE64_ENCODED_BINANCE_API_KEY"
  binance-api-secret: "REPLACE_WITH_BASE64_ENCODED_BINANCE_API_SECRET"
  
  # Webhook secret for secure communication (generate random string)
  webhook-secret: "REPLACE_WITH_BASE64_ENCODED_WEBHOOK_SECRET"
  
  # Web admin credentials (use strong, unique values)
  web-admin-user: "REPLACE_WITH_BASE64_ENCODED_ADMIN_USERNAME"
  web-admin-password: "REPLACE_WITH_BASE64_ENCODED_ADMIN_PASSWORD"
