apiVersion: v1
kind: Secret
metadata:
  name: trading-secrets
  namespace: alphabeta808-trading
type: Opaque
data:
  # Base64 encoded values - remplacez par vos vraies clés API
  # echo -n "your_binance_api_key" | base64
  binance-api-key: "eW91cl9iaW5hbmNlX2FwaV9rZXk="
  # echo -n "your_binance_api_secret" | base64  
  binance-api-secret: "eW91cl9iaW5hbmNlX2FwaV9zZWNyZXQ="
  # echo -n "your_webhook_secret" | base64
  webhook-secret: "eW91cl93ZWJob29rX3NlY3JldA=="
  # echo -n "admin" | base64
  web-admin-user: "YWRtaW4="
  # echo -n "secure_password_123" | base64
  web-admin-password: "c2VjdXJlX3Bhc3N3b3JkXzEyMw=="
